#!/usr/bin/env python3
"""
単一ソース static/data/allowed_symbols.json から
static/js/core/allowedSymbols.gen.js を生成する。

記号集合を変更したらこのスクリプトを実行し、生成ファイルをコミットすること。
expr_calc.py は JSON を直接読み、フロントは .gen.js を import する。
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON_PATH = ROOT / "static" / "data" / "allowed_symbols.json"
OUT_PATH = ROOT / "static" / "js" / "core" / "allowedSymbols.gen.js"


def main() -> int:
    if not JSON_PATH.is_file():
        print(f"Missing: {JSON_PATH}", file=sys.stderr)
        return 1
    raw = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    if not isinstance(raw, list) or not all(isinstance(x, str) and len(x) == 1 for x in raw):
        print("allowed_symbols.json must be a JSON array of single-character strings", file=sys.stderr)
        return 1
    # 安定した diff のためソート（表示・集合意味は同じ）
    data = sorted(raw)
    lines = [
        "// AUTO-GENERATED by tools/sync_allowed_symbols_from_json.py — do not edit",
        "// Source: static/data/allowed_symbols.json",
        f"export const ALLOWED_SYMBOL_LIST = {json.dumps(data, ensure_ascii=False)};",
        "export const ALLOWED_SYMBOL_CHARS = new Set(ALLOWED_SYMBOL_LIST);",
        "",
    ]
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(data)} symbols)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
